apiVersion: v1
kind: Template
metadata:
  name: loki

parameters:
- name: LOKI_HOST
  value: loki.loki
- name: LOKI_PORT
  value: "3100"

objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: promtail
    labels:
      helm.sh/chart: promtail-3.6.0
      app.kubernetes.io/name: promtail
      app.kubernetes.io/instance: promtail
      app.kubernetes.io/version: "2.2.1"
      app.kubernetes.io/managed-by: Helm
  stringData:
    promtail.yaml: |
      server:
        log_level: info
        http_listen_port: 3101

      client:
        url: http://${LOKI_HOST}:${LOKI_PORT}/loki/api/v1/push


      positions:
        filename: /run/promtail/positions.yaml

      scrape_configs:
        # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference

        # Pods with a label 'app.kubernetes.io/name'
        - job_name: kubernetes-pods-app-kubernetes-io-name
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # ignore logs from openshift-.* namespaces
            - action: drop
              regex: 'openshift-.*'
              source_labels:
                - __meta_kubernetes_namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
              target_label: app
            - action: drop
              regex: ''
              source_labels:
                - app
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_component
              target_label: component
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
              - namespace
              - app
              target_label: job
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
              target_label: __path__

        # Pods with a label 'app'
        - job_name: kubernetes-pods-app
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # ignore logs from openshift-.* namespaces
            - action: drop
              regex: 'openshift-.*'
              source_labels:
                - __meta_kubernetes_namespace
            # Drop pods with label 'app.kubernetes.io/name'. They are already considered above
            - action: drop
              regex: .+
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_app
              target_label: app
            - action: drop
              regex: ''
              source_labels:
                - app
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_component
              target_label: component
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
              - namespace
              - app
              target_label: job
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
              target_label: __path__

        # Pods with direct controllers, such as StatefulSet
        - job_name: kubernetes-pods-direct-controllers
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # ignore logs from openshift-.* namespaces
            - action: drop
              regex: 'openshift-.*'
              source_labels:
                - __meta_kubernetes_namespace
            # Drop pods with label 'app.kubernetes.io/name' or 'app'. They are already considered above
            - action: drop
              regex: .+
              separator: ''
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
            - action: drop
              regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
              source_labels:
                - __meta_kubernetes_pod_controller_name
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_controller_name
              target_label: app
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
              - namespace
              - app
              target_label: job
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
              target_label: __path__

        # Pods with indirect controllers, such as Deployment
        - job_name: kubernetes-pods-indirect-controller
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # ignore logs from openshift-.* namespaces
            - action: drop
              regex: 'openshift-.*'
              source_labels:
                - __meta_kubernetes_namespace
            # Drop pods with label 'app.kubernetes.io/name' or 'app'. They are already considered above
            - action: drop
              regex: .+
              separator: ''
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
            - action: keep
              regex: '[0-9a-z-.]+-[0-9a-f]{8,10}'
              source_labels:
                - __meta_kubernetes_pod_controller_name
            - action: replace
              regex: '([0-9a-z-.]+)-[0-9a-f]{8,10}'
              source_labels:
                - __meta_kubernetes_pod_controller_name
              target_label: app
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
              - namespace
              - app
              target_label: job
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
              target_label: __path__
        # All remaining pods not yet covered
        - job_name: kubernetes-other
          pipeline_stages:
            - cri: {}
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            # ignore logs from openshift-.* namespaces
            - action: drop
              regex: 'openshift-.*'
              source_labels:
                - __meta_kubernetes_namespace
            # Drop what has already been covered
            - action: drop
              regex: .+
              separator: ''
              source_labels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                - __meta_kubernetes_pod_label_app
            - action: drop
              regex: .+
              source_labels:
                - __meta_kubernetes_pod_controller_name
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: app
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_label_component
              target_label: component
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_node_name
              target_label: node_name
            - action: replace
              source_labels:
              - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              replacement: $1
              separator: /
              source_labels:
              - namespace
              - app
              target_label: job
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
              - __meta_kubernetes_pod_container_name
              target_label: container
            - action: replace
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
              target_label: __path__
            - action: replace
              regex: true/(.*)
              replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
              - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
              - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
              - __meta_kubernetes_pod_container_name
              target_label: __path__

- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: promtail
    labels:
      helm.sh/chart: promtail-3.6.0
      app.kubernetes.io/name: promtail
      app.kubernetes.io/instance: promtail
      app.kubernetes.io/version: "2.2.1"
      app.kubernetes.io/managed-by: Helm
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: promtail
    updateStrategy:
      {}
    template:
      metadata:
        labels:
          app.kubernetes.io/name: promtail
          app.kubernetes.io/instance: promtail
        annotations:
          checksum/config: 3faaea7b5fdc1f359409c4372e7f1fabf3af75f34372dcae0b41fabe214e3c9a
      spec:
        serviceAccountName: logcollector
        containers:
          - name: promtail
            image: "docker.io/grafana/promtail:2.2.1"
            imagePullPolicy: IfNotPresent
            args:
              - "-config.file=/etc/promtail/promtail.yaml"
            volumeMounts:
              - name: config
                mountPath: /etc/promtail
              - name: run
                mountPath: /run/promtail
              - mountPath: /var/lib/docker/containers
                name: containers
                readOnly: true
              - mountPath: /var/log/pods
                name: pods
                readOnly: true
            env:
              - name: HOSTNAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            ports:
              - name: http-metrics
                containerPort: 3101
                protocol: TCP
            securityContext:
              privileged: true
              readOnlyRootFilesystem: true
            readinessProbe:
              failureThreshold: 5
              httpGet:
                path: /ready
                port: http-metrics
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 1
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/master
            operator: Exists
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
            operator: Exists
        volumes:
          - name: config
            secret:
              secretName: promtail
          - name: run
            hostPath:
              path: /run/promtail
          - hostPath:
              path: /var/lib/docker/containers
            name: containers
          - hostPath:
              path: /var/log/pods
            name: pods
