apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: return-to-log
  annotations:
    app.openshift.io/connects-to: >-
      [{"apiVersion":"messaging.knative.dev/v1","kind":"Channel","name":"return-channel"},
       {"apiVersion":"serving.knative.dev/v1","kind":"Service","name":"log-funq"}
      ]
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: return-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: log-funq
