apiVersion: messaging.knative.dev/v1
kind: Channel
metadata:
  name: return-channel
---

apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: return.channel.subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: Channel
    name: return-channel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Broker
      name: default

